#config.yaml

enable_wifi_connect: 1 #是否开启wifi自动连接
enable_wifi_reconnect: 1 #是否开启wifi断线重连
max_wait_time: 10 #最大等待时间

wifi_config:
  username:  #学号
  password:  #密码


enable_mail_notification: 0 #是否开启邮件提醒


mail_config:
  mail_user:   #邮箱账号
  mail_pass:   #邮箱密码
  mail_host: smtp.exmail.qq.com  #邮箱服务器地址
  mail_port: 465  #邮箱服务器端口
  sender:   #发件人 往往和邮箱账号相同
  receivers:
    - #收件人 1



# Path: config.yaml