# Form implementation generated from reading ui file '.\mail_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(351, 401)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 360, 321, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 54, 16))
        self.label_2.setObjectName("label_2")
        self.mail_password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.mail_password.setGeometry(QtCore.QRect(100, 80, 191, 20))
        self.mail_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.mail_password.setObjectName("mail_password")
        self.mail_account = QtWidgets.QLineEdit(parent=self.groupBox)
        self.mail_account.setGeometry(QtCore.QRect(100, 40, 191, 20))
        self.mail_account.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.mail_account.setObjectName("mail_account")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 54, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 113, 191, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 210, 321, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 61, 16))
        self.label_5.setObjectName("label_5")
        self.SMTP_host = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.SMTP_host.setGeometry(QtCore.QRect(100, 39, 191, 21))
        self.SMTP_host.setObjectName("SMTP_host")
        self.SMTP_port = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.SMTP_port.setGeometry(QtCore.QRect(100, 79, 191, 21))
        self.SMTP_port.setObjectName("SMTP_port")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "邮件设置"))
        self.groupBox.setTitle(_translate("Dialog", "账号设置"))
        self.label.setText(_translate("Dialog", "邮箱账号"))
        self.label_2.setText(_translate("Dialog", "邮箱密码"))
        self.label_3.setText(_translate("Dialog", "收件人"))
        self.pushButton.setText(_translate("Dialog", "编辑收件人列表"))
        self.groupBox_2.setTitle(_translate("Dialog", "SMTP服务器设置"))
        self.label_4.setText(_translate("Dialog", "SMTP地址"))
        self.label_5.setText(_translate("Dialog", "SMTP端口"))
