# Form implementation generated from reading ui file '.\receivers_list.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 309)
        self.addButton = QtWidgets.QPushButton(parent=Dialog)
        self.addButton.setGeometry(QtCore.QRect(20, 210, 101, 31))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(parent=Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(20, 250, 151, 31))
        self.deleteButton.setObjectName("deleteButton")
        self.confirmButton = QtWidgets.QPushButton(parent=Dialog)
        self.confirmButton.setGeometry(QtCore.QRect(180, 250, 161, 31))
        self.confirmButton.setObjectName("confirmButton")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setGeometry(QtCore.QRect(20, 21, 321, 181))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 210, 211, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.listWidget, self.lineEdit)
        Dialog.setTabOrder(self.lineEdit, self.addButton)
        Dialog.setTabOrder(self.addButton, self.deleteButton)
        Dialog.setTabOrder(self.deleteButton, self.confirmButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "收件人列表"))
        self.addButton.setText(_translate("Dialog", "添加"))
        self.deleteButton.setText(_translate("Dialog", "删除"))
        self.confirmButton.setText(_translate("Dialog", "确认"))
